### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by elimae17** [liuch/dmarc-srg#108]
Excuse this naive question, but as I don't want to break anything, how do I update this application? Is it just a matter of replacing all the old files?

**Comment by williamdes** [comment]
As far as I use it with Docker images, yes

**Comment by liuch** [comment]
Yes, it is. There is no automatic update mechanism in the tool. You can set up your configuration manager for that, if you have one.

If you have a problem with updating because of this commit: https://github.com/liuch/dmarc-srg/commit/ea23bafae4c918831edb75e3e6883e0029e784d9, please note that you you need to change the path to the html root directory in your web server settings. This change is made to enhance security.

**Comment by Shnoulle** [comment]
> If you have a problem with updating because of this commit: [ea23baf](https://github.com/liuch/dmarc-srg/commit/ea23bafae4c918831edb75e3e6883e0029e784d9), please note that you you need to change the path to the html root directory in your web server settings. This change is made to enhance security.

I follow https://github.com/liuch/dmarc-srg/tags

Since it broke compatibility, next version must be 2.0, no ?

**Comment by liuch** [comment]
The version definitely needs to be changed. But I haven't made a release with this change yet.
