### ISSUE TITLE
Forensic reports?

### ISSUE THREAD

**Issue by 0x7466** [liuch/dmarc-srg#120]
Hi, really cool project!

I was wondering, does this project also support forensic reports that get sent if the `ruf=` tag is set?

Thanks for your Open Source contribution! 🙂

**Comment by liuch** [comment]
Hi, Thank you for your attention to my project.
Unfortunately the project doesn't support RUF reports. Most major mail servers do not send RUF reports because of sensitive information and I've never come across these reports on my server. It seems to me that this is not a priority functionality. Maybe I'll implement it later.

**Comment by 0x7466** [comment]
OK great thanks for the info. :)

**Comment by williamdes** [comment]
Ref: #26
Should you also close #26 @liuch ?
I agree that I never receive RUF reports too. Seems like nobody is sending them in the recent years.

**Comment by liuch** [comment]
@williamdes, I left it open that time as a TODO entry in case I had time to implement it. Now I think you're right, there's little chance of me implementing it.
