### ISSUE TITLE
Feature Request - Reporting Statistics When Filtered

### ISSUE THREAD

**Issue by andrewhenke** [liuch/dmarc-srg#62]
Hello! I have noticed that when filtering reports to view, the global number of emails and the percentage of DMARC compliant emails, partially compliant emails, etc, does not update when only viewing a specific domain's records. Would it be possible to update this tool so that when filtering to view DMARC reports for just a single domain name, the global statistics are updated to reflect the compliance and percent of compliance out of just the individual domain's reports? 

Thank you!

**Comment by liuch** [comment]
Hello. How do you imagine it? After all, these numbers are displayed not only on the report list page where you can use the filter. Do you mean to use the filter when you are on the report list page, and disable filtering when you leave it?

**Comment by andrewhenke** [comment]
Thank you for the quick response! Here is my example: 

On the main page, showing the overview of all DMARC reports within the system, for multiple different domain names, there is the following statistics section, in the upper right corner of the page: 

<img width="171" alt="image" src="https://user-images.githubusercontent.com/24320242/234060395-181ff17b-7db3-4c44-a5b9-2bd4ac8d8100.png">


When I go to the `List display settings` menu. and select to the filter `domain`, and select the domain `example.com`, the statistics section does not update to show the statistics about the specific domain that is selected -- it still shows the global, system wide statistics for all domains. 

I propose adding the feature so that, when filtering by a specific domain, the statistics boxes show only the numbers relevant to the specific domain name that is being filtered, instead of the system-wide details. 

For example, if the domain `example.com` only sent 10000 emails, the `Emails processed` box would show 10000, instead of, in the case of my system, 178759. 

Likewise, if `example.com` had all of it's emails stating that the domain was fully aligned with the DMARC specifications, then the `Fully aligned` percentage would update to show 100%, instead of the system-wide value. 

Does that make more sense? 

Please feel free to ask me to clarify further if I am not coming across clearly. 

Thank you!

**Comment by liuch** [comment]
Perhaps, I didn't express myself clearly enough. I'll try to ask differently. For example, step by step.

1. The filter by domain now is inactive (all domains). I'm not on the report list page. Let it be the summary reports page.  The statistics sections displays numbers X1.X2.X3.X4.
2. I go to the report list page and set the filter by one domain. Now the statistics sections displays numbers Y1.Y2.Y3.Y4. 
3. Then I return to the summary reports page through the main menu. Which numbers should be displayed in the statistics section, X1.X2.X3.X4 or Y1.Y2.Y3.Y4? At the same time, note that, with the exception of the statistics block, the page at this step doesn't differ in any way from the page at the first step.
4. Which numbers should be displayed in the statistics section if I go there by clicking the back button in my browser?
5. Then I go to the report list page again through the main menu. What should be displayed there? Please note that the filter is inactive in this case.

I want to clarify: I am asking these questions not in an attempt to criticize your idea, but in order to better understand it.

**Comment by liuch** [comment]
@mbsouth, You suggest that the filter for those numbers in the statistic section work only on one page (report list) and only when the filter is activated. Any transition to other pages should reset these numbers to the global values? Did I understand you correctly?

> No, it doesn't. The global values X1.X2.X3.X4 are still displayed.
> In my example, only 8 messages are supposed to be processed from this domain not 1306.

All what i wrote in my previous comment was hypothetical (what exactly the tool should do). Perhaps I expressed my thought incorrectly. I just offered to follow the same steps and tell me which numbers you think should be displayed at each step in that block.

Thank you for your reply.

**Comment by liuch** [comment]
Implemented. Now any filtering parameter affects the top block. I will add an option to the settings later.

**Comment by mbsouth** [comment]
@liuch 

Thanks for the implementation!

Unfortunately it seems there is a small bug: if the filter **Month = Any** is set, the totals are not correct.

But otherwise exactly as I imagined it. Thx!

**Comment by liuch** [comment]
If the filter Month = Any is set then the option `status.emails-for-last-n-days` is used.

**Comment by mbsouth** [comment]
Ah, thanks!
