### ISSUE TITLE
Unable to donate

### ISSUE THREAD

**Issue by williamdes** [liuch/dmarc-srg#71]
Hi @liuch 

I could not donate on PayPal, on the confirm screen it said to contact the PayPal assistance..
Can you setup GitHub sponsors ?

**Comment by mayall** [comment]
I'll second this request. DMARC-SRG is terrific and I'd like to acknowledge Aleksey's work with a contribution.

**Comment by williamdes** [comment]
It's been years since I am searching for such a tool, this one is so simple, clean and easy to deploy!
Pure PHP and JS, clean and working! 
I even made a docker version, let me know if I should contribute it here
DMARC-SRG is the tool my company needed for so long, I really want to bring support to this project

**Comment by liuch** [comment]
Thanks for your support including your kind words. I'm afraid that the problem is that PayPal has stopped accepting donations for Russian citizens. Of course I can try to connect GitHub sponsors, but I'm not sure if this will help given my citizenship.

**Comment by williamdes** [comment]
Maybe you have a bank that has some nice ways to donate?
Not sure if it's safe to share the bank account number?

**Comment by schleup** [comment]
so sorry, I also tried to donate but PayPal didn't accept :-(

**Comment by liuch** [comment]
My region is not supported by  the GitHub Sponsors, they added me on the waitlist. But I don't think this will change anytime soon. I have just looked at several ways to receive donations, there are problems with each of them for the Russians. Right now I have no idea about this, maybe I'll come up with something later. A direct transfer to a bank account does not seem like a good idea to me, because there can be problems for both the sender and the recipient. Thank you again for the offer. I appreciate it.

**Comment by SteelPC** [comment]
Just discovered this project and it is just awesome ! I am not able to donate either from France .... Let me know as soon as this is solved :D

**Comment by Shnoulle** [comment]
> Maybe you have a bank that has some nice ways to donate? Not sure if it's safe to share the bank account number?

I think European and US can not send money to Russian citizen currently.

I love this tool @liuch , maybe try with https://opencollective.com/ or https://liberapay.com/ ? But i thnink the problem is same for all ...

**Comment by williamdes** [comment]
I am no keep this one open, feel free to post here when you have a donation button ;)
